import Text from './Text';
import Button from './Button';
import Select from './Select';
import Dropdown from './Dropdown';
import Checkbox from './Checkbox';
import Radio from './Radio';
import Toggle from './Toggle';
import Pagination from './Pagination';
import Breadcrumbs from './Breadcrumbs';
import Tag from './Tag';
import Lozenge from './Lozenge';
import InlineMessage from './InlineMessage';
import Callout from './Callout';
import Banner from './Banner';
import InlineDialog from './InlineDialog';
import Badge from './Badge';
import Progress from './Progress';
import Avatar from './Avatar';
import Tooltip from './Tooltip';
import Spinner from './Spinner';
import Tab from './Tab';
import Heading from './Heading';
import Color from './Color';

const Components = (catalog) => {
  catalog.add(Text);
  catalog.add(Button);
  catalog.add(Select);
  catalog.add(Dropdown);
  catalog.add(Checkbox);
  catalog.add(Radio);
  catalog.add(Toggle);
  catalog.add(Pagination);
  catalog.add(Breadcrumbs);
  catalog.add(Tag);
  catalog.add(Lozenge);
  catalog.add(InlineMessage);
  catalog.add(Callout);
  catalog.add(Banner);
  catalog.add(InlineDialog);
  catalog.add(Badge);
  catalog.add(Progress);
  catalog.add(Avatar);
  catalog.add(Tooltip);
  catalog.add(Spinner);
  catalog.add(Tab);
  catalog.add(Heading);
  catalog.add(Color);
};

export default Components;
